// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3_lMtFfCa3uuE8Yw1VwCCDuzXMKYsddc',
    appId: '1:601319923005:web:c7060c1f53dc03e4507954',
    messagingSenderId: '601319923005',
    projectId: 'adv-exam-aada7',
    authDomain: 'adv-exam-aada7.firebaseapp.com',
    storageBucket: 'adv-exam-aada7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-YjG1HNlDNS6YolLz9dUHIZ-D4-LEbDA',
    appId: '1:601319923005:android:01cc9ef0eeeab753507954',
    messagingSenderId: '601319923005',
    projectId: 'adv-exam-aada7',
    storageBucket: 'adv-exam-aada7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg1BIX2NicwMgjbneGOLwfnziR8bXVjUQ',
    appId: '1:601319923005:ios:63b32994ae552096507954',
    messagingSenderId: '601319923005',
    projectId: 'adv-exam-aada7',
    storageBucket: 'adv-exam-aada7.appspot.com',
    iosBundleId: 'com.example.advExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg1BIX2NicwMgjbneGOLwfnziR8bXVjUQ',
    appId: '1:601319923005:ios:63b32994ae552096507954',
    messagingSenderId: '601319923005',
    projectId: 'adv-exam-aada7',
    storageBucket: 'adv-exam-aada7.appspot.com',
    iosBundleId: 'com.example.advExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3_lMtFfCa3uuE8Yw1VwCCDuzXMKYsddc',
    appId: '1:601319923005:web:9f3a599426849aec507954',
    messagingSenderId: '601319923005',
    projectId: 'adv-exam-aada7',
    authDomain: 'adv-exam-aada7.firebaseapp.com',
    storageBucket: 'adv-exam-aada7.appspot.com',
  );
}
